config/routes.rb
Cycles::Application.routes.draw do
  resources :apps

  resources :ideas do
    resources :comments, :except => [:index, :show, :new]
    resources :votes, :only => [:create]
    
    collection do
      get :cycling
      get :implemented
      get :scrapped
    end
    
    member { put :escalate }
  end

  resources :people
  
  root  :to => 'ideas#index'

end

app/models/idea.rb
class Idea < AbstractIdea
  include RankedModel

  accepts_nested_attributes_for :comments
  
  attr_accessible :comments_attributes
  
  scope :escalated, where(:escalated => true)
  scope :normal, where(:escalated => false)

  ranks :priority
  
  def already_voted?(person)
    voters.include?(person)
  end
  
  def move_up
    reload
    item = self.class.where(['votes_count > ?',votes_count]).last
    update_attribute(:priority,item.priority+1)
  end
  
  def scrap
    update_attribute(:type,'ScrappedIdea')
  end
  
  def cycle
    update_attribute(:type,'CyclingIdea')
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # GET /ideas
  def index
    @escalated = Idea.escalated.rank(:priority).includes(:app,:creator)
    @normal = Idea.normal.rank(:priority).includes(:app,:creator)
  end
  
  # GET /ideas/cycling
  def cycling
    @ideas = CyclingIdea.includes(:app,:creator)
    
    render :index
  end

  # GET /ideas/implemented
  def implemented
    @ideas = ImplementedIdea.includes(:app,:creator)
    
    render :index
  end

  # GET /ideas/scrapped
  def scrapped
    @ideas = ScrappedIdea.includes(:app,:creator)
    
    render :index
  end

  # GET /ideas/1
  def show
    @idea = AbstractIdea.includes(:app,{ :comments => :creator },:voters,:creator).find(params[:id])
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
    @idea.comments.build
  end

  # GET /ideas/1/edit
  def edit
    @idea = current_user.ideas.find(params[:id])
  end

  # POST /ideas
  def create
    @idea = current_user.ideas.build(params[:idea])

    if @idea.save
      redirect_to(@idea, :notice => 'Idea was successfully created.')
    else
      render :new
    end
  end

  # PUT /ideas/1
  def update
    @idea = current_user.ideas.find(params[:id])

    if @idea.update_attributes(params[:idea])
      redirect_to(@idea, :notice => 'Idea was successfully updated.')
    else
      render :edit
    end
  end

  # PUT /ideas/1/escalate  
  def escalate
    @idea = Idea.find(params[:id])
    @idea.toggle!(:escalated)

    up_or_down = @idea.escalated? ? 'escalated' : 'downgraded'
    
    redirect_to(@idea)
  end

  # DELETE /ideas/1
  def destroy
    @idea = current_user.ideas.find(params[:id])
    @idea.scrap

    redirect_to(ideas_url, :notice => 'Idea was successfully scrapped.')
  end
end

app/helpers/ideas_helper.rb
#encoding: utf-8
module IdeasHelper
  def app_options
    App.all.collect {|a| [a.name, a.id] }
  end
  
  def back_to_ideas_link(idea)
    case
    when idea.is_a?(Idea)
      type = 'shared'
      path = ideas_path
    when idea.is_a?(CyclingIdea)
      type = 'cycling'
      path = cycling_ideas_path
    when idea.is_a?(ImplementedIdea)
      type = 'implemented'
      path = implemented_ideas_path
    when idea.is_a?(ScrappedIdea)
      type = 'scrapped'
      path = scrapped_ideas_path
    end
    
    link_to("← Back to #{type} ideas", path, :id => 'link-back')
  end
  
  def cycle_button(idea)
    unless idea.implemented?
      if idea.cycling?
        button_to 'Implemented', '#', :class => 'gray button smallest'
      else
        button_to 'Start cycle', '#', :class => 'gray button smallest'
      end
    end
  end
  
  def escalate_button(idea)
    escalate_text = idea.escalated? ? 'De-escalate' : 'Escalate'
    button_to escalate_text, escalate_idea_path(idea), :method => :put, :confirm => 'Are you sure?', :class => 'gray button smallest' if idea.escalateable?
  end
  
  def escalated_or_votes(idea)
    if idea.escalated?
      "escalated"
    else
      "#{idea.votes_count} votes"
    end
  end
  
  def ideas_nav
    nav = ''.html_safe
    nav += link_to_unless_current 'shared', ideas_path
    %w(cycling implemented scrapped).each do |type|
      nav += link_to_unless_current(type, eval("#{type}_ideas_path"))
    end
    nav
  end
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h3>
      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title, 'Give it a name' %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
  <%= f.fields_for :comments do |ff| %>
    <%= ff.label :body, 'Describe it' %>
    <%= ff.text_area :body %>
  <% end %>
  </div>
  <div class="field">
    <%= f.label :app_id, 'Does it relate to an app?' %>
    <%= f.select :app_id, app_options, :include_blank => true %>
  </div>
  <div class="actions">
    <%= f.submit 'Add this idea', :class => 'gray button smaller' %> <small>or <%= link_to('Cancel',:back) %></small>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<%= link_to 'Back to all ideas', ideas_path %> | <%= link_to 'Delete this idea', @idea, :confirm => 'Are you sure?', :method => :delete %>

<h1>Editing <%= @idea.name %></h1>

<%= render 'form' %>

app/views/ideas/index.html.erb
<nav class="links">
    <%= ideas_nav %>
</nav>
<%= button_to 'Share an idea', new_idea_path, :method => :get, :class => 'button', :id => 'share' %>
<h1><%= action_name unless action_name == 'index' %> ideas</h1>
<div id="ideas">
<% @escalated.each do |idea| %>
    <%= link_to idea_path(idea) do %>
        <div class="idea">
            <h3><%= idea.title %> <small><em><%= idea.app.name %></em></small></h3>
            <p>Shared by <%= idea.creator.name %> &#8212; <%= escalated_or_votes(idea) %></p>
        </div>
    <% end %>
<% end %>
<% @normal.each do |idea| %>
    <%= link_to idea_path(idea) do %>
        <div class="idea">
            <h3><%= idea.title %> <small><em><%= idea.app.name %></em></small></h3>
            <p>Shared by <%= idea.creator.name %> &#8212; <%= escalated_or_votes(idea) %></p>
        </div>
    <% end %>
<% end %>
</div>

app/views/ideas/new.html.erb
<h2>Share a new idea</h2>
<%= render 'form' %>

app/views/ideas/show.html.erb
<section id="idea">
    <%= back_to_ideas_link(@idea) %>
    <% if @idea.app.present? %>
    <h4 class="app"><%= @idea.app.name %></h4>
    <% end %>
    <h2><%= @idea.title %></h2>
    <p>Shared by <%= @idea.creator.name %></p>
    <p class="comment"><%= @idea.comments.shift.body %></p>
    <% @idea.comments.each do |comment| %>
    <p class="comment"><strong><%= comment.creator.name %> said:</strong><br/> <%= comment.body %></p>
    <% end %>
    <%= button_to '+1', idea_votes_path(@idea), :method => :post, :class => 'gray button smallest' if @idea.votable? && !@idea.already_voted?(current_user)  %>
    <%= cycle_button(@idea) %>
    <%= escalate_button(@idea) %>
    <%= button_to 'Scrap this idea', idea_path(@idea), :method => :delete, :confirm => 'Are you sure?', :class => 'gray button smallest' if @idea.scrappable?  %>
    <%= form_for :comment, :url => idea_comments_path(@idea), :html => { :id => 'new_comment' } do |f| %>
        <div class="field">
            <%= f.label :body, 'Leave a comment...' %>
            <%= f.text_area :body %>
        </div>
        <div class="actions">
            <%= f.submit 'Add this comment', :class => 'gray button smaller' %>
        </div>
    <% end unless @idea.implemented? %>
</section>
<aside id="people">
  <h4><%= @idea.votes_count || 'no' %> votes</h4>
<% @idea.voters.each do |voter| %>
    <%= voter.name %> +1<br/>
<% end %>
</aside>