config/routes.rb
Cycles::Application.routes.draw do
  resources :apps

  resources :ideas do
    resources :comments, :except => [:index, :show, :new]
    resources :votes, :only => [:create]
    
    collection do
      get :cycling
      get :implemented
      get :scrapped
    end
    
    member { put :escalate }
  end

  resources :people
  
  root  :to => 'ideas#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :creator, :class_name => 'Person', :foreign_key => :created_by
  belongs_to :idea, :counter_cache => true
    
  attr_accessible :body

  validates_presence_of :body, :idea_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments/1/edit
  def edit
    @comment = current_user.comments.find(params[:id])
  end

  # POST /ideas/1/comments
  def create
    @comment = current_idea.comments.build(params[:comment])

    if @comment.save
      flash[:notice] = 'Comment was successfully created.'
    end

    redirect_to(current_idea)
  end

  # PUT /comments/1
  def update
    @comment = current_user.comments.find(params[:id])

    if @comment.update_attributes(params[:comment])
      redirect_to(current_idea, :notice => 'Comment was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /comments/1
  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy

    redirect_to(current_idea)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :idea_id %><br />
    <%= f.text_field :idea_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>